# 그림판(캔버스) 좌표
canvas:
  corner1:
    world: world
    x: 100.5
    y: 64.0
    z: -20.5
  corner2:
    world: world
    x: 120.5
    y: 70.0
    z: 0.5

# 좀비 소환 위치
zombie_spawn:
  world: world_nether
  x: 200.0
  y: 80.0
  z: 200.0

# 감옥 입장/해제 위치
jail:
  world: world
  x: 50.0
  y: 65.0
  z: 50.0
release:
  world: world
  x: 55.0
  y: 65.0
  z: 55.0

# 블럭상자
unlimited-chests:
  - world: world
    x: 58
    y: -50
    z: 50
    slots:
      0:
        material: WHITE_CONCRETE
        amount: 64
      1:
        material: LIGHT_GRAY_CONCRETE
        amount: 64
      2:
        material: GRAY_CONCRETE
        amount: 64
      3:
        material: BLACK_CONCRETE
        amount: 64
      4:
        material: BROWN_CONCRETE
        amount: 64
      5:
        material: RED_CONCRETE
        amount: 64
      6:
        material: ORANGE_CONCRETE
        amount: 64
      7:
        material: YELLOW_CONCRETE
        amount: 64
      8:
        material: LIME_CONCRETE
        amount: 64
      9:
        material: GREEN_CONCRETE
        amount: 64
      10:
        material: CYAN_CONCRETE
        amount: 64
      11:
        material: LIGHT_BLUE_CONCRETE
        amount: 64
      12:
        material: BLUE_CONCRETE
        amount: 64
      13:
        material: PURPLE_CONCRETE
        amount: 64
      14:
        material: MAGENTA_CONCRETE
        amount: 64
      15:
        material: PINK_CONCRETE
        amount: 64
      18:
        material: WHITE_CONCRETE_POWDER
        amount: 64
      19:
        material: LIGHT_GRAY_CONCRETE_POWDER
        amount: 64
      20:
        material: GRAY_CONCRETE_POWDER
        amount: 64
      21:
        material: BLACK_CONCRETE_POWDER
        amount: 64
      22:
        material: BROWN_CONCRETE_POWDER
        amount: 64
      23:
        material: RED_CONCRETE_POWDER
        amount: 64
      24:
        material: ORANGE_CONCRETE_POWDER
        amount: 64
      25:
        material: YELLOW_CONCRETE_POWDER
        amount: 64
      26:
        material: LIME_CONCRETE_POWDER
        amount: 64
      27:
        material: GREEN_CONCRETE_POWDER
        amount: 64
      28:
        material: CYAN_CONCRETE_POWDER
        amount: 64
      29:
        material: LIGHT_BLUE_CONCRETE_POWDER
        amount: 64
      30:
        material: BLUE_CONCRETE_POWDER
        amount: 64
      31:
        material: PURPLE_CONCRETE_POWDER
        amount: 64
      32:
        material: MAGENTA_CONCRETE_POWDER
        amount: 64
      33:
        material: PINK_CONCRETE_POWDER
        amount: 64
      36:
        material: MAGENTA_TERRACOTTA
        amount: 64
      37:
        material: PINK_TERRACOTTA
        amount: 64
      38:
        material: PURPLE_TERRACOTTA
        amount: 64
      39:
        material: BLUE_TERRACOTTA
        amount: 64
      40:
        material: LIGHT_BLUE_TERRACOTTA
        amount: 64
      41:
        material: CYAN_TERRACOTTA
        amount: 64
      42:
        material: LIME_TERRACOTTA
        amount: 64
      43:
        material: GREEN_TERRACOTTA
        amount: 64
      44:
        material: YELLOW_TERRACOTTA
        amount: 64
      45:
        material: RED_TERRACOTTA
        amount: 64
      46:
        material: ORANGE_TERRACOTTA
        amount: 64
      47:
        material: TERRACOTTA
        amount: 64
      48:
        material: WHITE_TERRACOTTA
        amount: 64
      49:
        material: LIGHT_GRAY_TERRACOTTA
        amount: 64
      50:
        material: GRAY_TERRACOTTA
        amount: 64
      51:
        material: BROWN_TERRACOTTA
        amount: 64
      52:
        material: BLACK_TERRACOTTA
        amount: 64